/*
SQLyog Community v13.1.1 (64 bit)
MySQL - 5.7.17 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('1','USER','blackListRuleImpl','用户黑名单','命中黑名单则拒','','','1','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('2','USER','repeatLoanRuleImpl','复贷规则','逾期7天（含）内足额还款的，可以复借；逾期超过7天的不论是否足额还款，不予再借；','7','','2','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('3','DEVICE','simulatorRuleImpl','手机模拟器检测','命中模拟器则拒','','','3','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('4','CERT','ageRuleImpl','年龄范围检查','年龄20-45（含），不在范围内的拒','20','45','4','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('5','MOBILE','addressBookRuleImpl','通讯录规则',' 通讯录有效手机号码（13、14、15、17、18开头，11位）不足20条（含）则拒绝','20','','5','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('6','MOBILE','virtualMobileRuleImpl','虚拟号段拒','虚拟号段拒','','','6','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('7','LOCATION','locationRuleImpl','位置规则','GPS当前省份是西藏、新疆则拒','西藏#新疆','','7','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('8','LOCATION','addressRuleImpl','户籍地址规则','身份证户籍身份是西藏、新疆则拒','西藏#新疆','','8','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('9','DEVICE','deviceRuleImpl','设备规则','iphone5s及以下的拒绝；安卓手机，内存低于1G的则拒；安卓手机，磁盘低于4G的则拒； 安卓手机，厂商不是在数据字典中的拒；','1#4','','9','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('10','REPORT','blackAgencyRuleImpl','黑中介规则','黑中介分数 x < 40：拒绝','40','','10','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('11','REPORT','courtBlackListRuleImpl','法院黑名单','申请人姓名+身份证号码是否出现在法院黑名单 是：拒绝','','','11','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('12','REPORT','financialNameCertBlackListRuleImpl','金融机构黑名单1','申请人姓名+身份证号码是否出现在金融机构黑名单 是：拒绝','','','12','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('13','REPORT','financialNameMobileBlackListRuleImpl','金融机构黑名单2','申请人姓名+手机号码是否出现在金融机构黑名单 是：拒绝','','','13','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('14','REPORT','collectionCallSecondRuleImpl','与催收公司通话时长','近6月与催收公司通话时长（秒） x>=240：拒绝','240','','14','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('15','REPORT','collectionCallTimesRuleImpl','与催收公司通话次数','近6月与催收公司通话次数 x>3：拒绝','3','','15','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('16','REPORT','contactsBlackListRuleImpl','联系人中黑名单','直接联系人中黑名单人数 > 4 拒绝','4','','16','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('17','REPORT','zhimaScoreRuleImpl','芝麻信用分规则','芝麻信用分 >590 通过','590','','17','DEL','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('18','USER','singleMobileRuleImpl','手机号单一性规则','一个手机号下只可存在一笔待审批的申请；一个手机号下只可存在一笔未结清的贷款。','','','18','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('19','DEVICE','singleDeviceRuleImpl','设备单一性规则','一个设备只可存在一笔待审批的申请;一个设备只可存在一笔未结清的贷款。','','','19','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('20','CERT','certValidityRuleImpl','身份证有效性规则','不接受临时(若证件有效期为一个月，则认定为临时身份证，拒绝该申请)、过期身份证','30','','20','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('21','USER','jobRuleImpl','职业规则','若借款人的职业为“在校学生”或“无收入来源”，则拒绝申请','','','21','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('22','REPORT','internalBlackListRule1Impl','内部黑名单核查规则1','借款人运营商常用联系人(近1个月内有过3次及以上通话记录)不得在我司内部黑名单中','1','3','22','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('23','USER','internalBlackListRule2Impl','内部黑名单核查规则2','根据身份证解析的户籍地址，一个地址下只可有一笔未结清的订单','','','23','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('24','USER','internalBlackListRule3Impl','内部黑名单核查规则3','对于逾期超过30天的借款人的户籍地址，加入我司户籍地址黑名单。新的借款申请不得击中户籍地址黑名单。','','','24','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('25','CERT','nationlityRuleImpl','民族规则','排除藏族、新疆及维吾尔族的借款人','藏#维吾尔','','25','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('26','USER','historyLoanRuleImpl','内部历史借贷情况核查规则 + 在途验证','有贷款未结清，则拒绝；已结清的借款曾单期逾期超过30天，拒绝；','30','','26','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('27','MOBILE','mobileRealNameRuleImpl','手机号实名认证规则','手机号非实名则拒绝','','','27','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('28','REPORT','crawlerBlackListRuleImpl','爬虫黑名单规则','命中爬虫公司黑名单则拒绝','','','28','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('29','MOBILE','mobileOpenTimeRuleImpl','手机号入网时长规则','手机号在网时长不应少于6个月(180天)','180','','29','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('30','REPORT','cashLoan30dRuleImpl','魔杖30天多头申请规则','cash_loan_30d>12,拒绝','12','','30','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('31','REPORT','cashLoan15dRuleImpl','魔杖15天多头申请规则','cash_loan_15d>10,拒绝','10','','31','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('32','REPORT','carrierModelScoreRuleImpl','运营商模型评分规则','运营商评分<=574，拒绝','-28.85#481.86','550','32','DEL','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('33','REPORT','moxieModelScoreRuleImpl','魔蝎模型分规则','魔蝎魔杖评分<=608,拒绝','608','','33','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('34','USER','postSwitchRuleImpl','后置开关规则','最后返回一律拒绝','','','34','NOR','0','0');
insert into `risk_control_rule` (`id`, `ruleType`, `ruleImpl`, `ruleName`, `ruleDesc`, `param1`, `param2`, `sort`, `stat`, `addTime`, `updateTime`) values('35','REPORT','carrierModelScoreJxlRuleImpl','运营商模型(聚信立)评分规则','运营商评分<=574，拒绝','-28.85#481.86','547','32','NOR','0','0');