spring:

  #数据库连接配置
  datasource:
    url: jdbc:p6spy:mysql://rm-uf633218w58wy2ksyrw.mysql.rds.aliyuncs.com:3306/jmloan?allowMultiQueries=true&characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
    username: jmloan
    password: uZlApDeCmQcT6Zmj56vhqTxIslT6Km1B
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  #缓存配置
  redis:
    host: r-uf663a502ae311e4.redis.rds.aliyuncs.com
    port: 6379
    password: Jhxyredis2018
      #jedis:
      #pool:
      #max-idle: 200
    #max-wait: 10000
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 10000
    block-when-exhausted: true
      #sentinel:
      #master: mymaster
    #nodes: 172.19.36.239:26379
myOriginUrl: http://localhost:9628