app:
  name: uranussv

spring:
  profiles:
    active: dev # 当前激活环境
  application:
    name: uranussv

# web服务配置
server:
  port: 50808
  servlet:
    context-path: /uranussv

# json配置
jackson:
  time-zone: Asia/Shanghai
  default-property-inclusion: non_null #如果值为null，则不参与序列化

http:
  encoding:
    force: true

# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.jieandata.uranussv.dal.model

# 数据库连接池配置
hikari:
  connection-timeout: 30000
  idle-timeout: 600000
  max-lifetime: 1800000
  maximum-pool-size: 10
  connection-test-query: SELECT 1

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql