spring:
  #数据库连接配置
  datasource:
    url: jdbc:p6spy:mysql://10.6.8.228:3306/saturn?allowMultiQueries=true&characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
    username: saturnuser
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #缓存配置172.19.36.239
  redis:
    host: 47.100.45.99
    port: 6379
    password: jhxyredis
    #jedis:
      #pool:
        #max-idle: 200
        #max-wait: 10000
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 10000
    block-when-exhausted: false
    #sentinel:
      #master: mymaster
      #nodes: 172.19.36.239:26379
myOriginUrl: http://localhost:9628



